version: "3.7"

services:
  test:
    build: .
    image: rsp_5_0
    command: /bin/bash -c 'service postgresql start && rake test'
    volumes:
      - '.:/app'

  test_3_0:
    build:
      context: .
      dockerfile: Dockerfile_30
    image: rsp_5_3_0
    command: /bin/bash -c 'service postgresql start && rake test'
    volumes:
      - '.:/app'

