version: "3.7"

services:
  test:
    build: .
    image: niceql
    command: /bin/bash -c 'service postgresql start && rake test'
    volumes:
      - '.:/app'

  test_3_0:
    build:
      context: .
      dockerfile: Dockerfile_30
    image: niceql_3_0
    command: /bin/bash -c 'service postgresql start && rake test'
    volumes:
      - '.:/app'

  test_3_1:
    build:
      context: .
      dockerfile: Dockerfile_3_1
    image: niceql_3_1
    command: /bin/bash -c 'service postgresql start && rake test'
    volumes:
      - '.:/app'
